import { answers } from "@/data/answers";
import type { Answer, Context } from "@/types";
import type { AskProvider, AskResult } from "./provider";

// Short pause so the loading state is visible, as it would be with a network call.
const SIMULATED_DELAY_MS = 500;

// Wording that means the question is about Singapore, whatever the selector says.
const SG_SIGNALS = ["singapore", "sgds", "singpass", "government service", "government website", "govtech"];

function normalise(text: string): string {
  return text.toLowerCase().replace(/[^a-z0-9\s]/g, " ").replace(/\s+/g, " ").trim();
}

function best(question: string, pool: Answer[]): Answer | null {
  let winner: Answer | null = null;
  let winnerHits = 0;
  for (const answer of pool) {
    const hits = answer.triggers.filter((t) => question.includes(t)).length;
    if (hits > winnerHits) {
      winner = answer;
      winnerHits = hits;
    }
  }
  // A single matching word is too weak to claim an answer.
  return winnerHits >= 2 ? winner : null;
}

function match(question: string, chosen: Context): AskResult {
  const q = normalise(question);
  const detected = chosen !== "sg" && SG_SIGNALS.some((signal) => q.includes(signal));
  const context: Context = detected ? "sg" : chosen;
  if (!q) return { answer: null, context, contextDetected: false };

  const exact = answers.find((a) => normalise(a.question) === q);
  if (exact) return { answer: exact, context: exact.context ?? context, contextDetected: detected };

  const regional = answers.filter((a) => a.context === context);
  const global = answers.filter((a) => !a.context);
  // In a region, its own answers come first; global ones fill the gaps.
  const answer = (context === "global" ? null : best(q, regional)) ?? best(q, global);
  return { answer, context, contextDetected: detected };
}

export const localProvider: AskProvider = {
  description: "Answered from Shortcut's hand-written reference set. No text was generated by a model.",
  ask(question, { context }) {
    return new Promise((resolve) => setTimeout(() => resolve(match(question, context)), SIMULATED_DELAY_MS));
  },
};
